#!/bin/bash

set -x

pdsh -w mr-fusion[$1-$2] 'ls -la /tmp/.geopm* 2> /dev/null' 2> /dev/null
pdsh -w mr-fusion[$1-$2] 'ls -la /dev/shm/brg-* 2> /dev/null' 2> /dev/null
pdsh -w mr-fusion[$1-$2] 'ls -la /dev/shm/geopm-* 2> /dev/null' 2> /dev/null

read -p "Press any key to continue..." -n1 -s
echo
pdsh -w mr-fusion[$1-$2] 'rm /tmp/.geopm* 2> /dev/null' 2> /dev/null
pdsh -w mr-fusion[$1-$2] 'rm /dev/shm/brg-* 2> /dev/null' 2> /dev/null
pdsh -w mr-fusion[$1-$2] 'rm /dev/shm/geopm-* 2> /dev/null' 2> /dev/null
